### ISSUE TITLE
Таблица, выравнивание текста

### ISSUE THREAD

**Issue by tsukasa-mixer** [studio107/ueditor-fork#10]
Сейчас в таблицах горизонтальное выравнивание задается с помощью свойства align, но если в глобальных стилях (css) задано свойством text-align то данное свойство игнорируется.
(т.к. мы используем foundation то выравнивание в css будет всегда задано)

тут нужно решить что делать:
1 - возможно изменить внесение значения с свойства align на внесение в style для элемента
2 - Разобраться возможно-ли браузеру подсказать что выравнивание задано в align (пока нифига не получается согласно значениям есть вариации, стартовое значение и наследуемое)
3 - Разобраться с настройками foundation (судя по кишкам там используется $default-float параметр с флагом !default т.е. перекрываемое, но перекрытие данного параметра в _settings не дает результата.)

**Comment by tsukasa-mixer** [comment]
Пока спасаюсь таким макером

```SCSS
table {
  tr {
    th,
    td {
      &[align='left'] {
        &, & > * { text-align: left; }
      }
      &[align='center'] {
        &, & > * { text-align: center; }
      }
      &[align='right'] {
        &, & > * { text-align: right; }
      }
      &[align='justify'] {
        &, & > * { text-align: justify; }
      }

    }

    th {
      &, & > * {
        font-weight: bold
      }
    }
  }
}
```
